# Generated by Django 3.0.8 on 2021-04-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='tag',
            field=models.CharField(blank=True, default='common', max_length=255, null=True),
        ),
    ]
