# Generated by Django 3.0.8 on 2021-04-14 06:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='tag',
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(blank=True, default='common', max_length=255, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_blogs', to='blogs.Blogs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
