# Generated by Django 3.0.8 on 2021-04-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210414_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tag',
        ),
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(to='blogs.Tags'),
        ),
        migrations.AddField(
            model_name='tags',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
