# Generated by Django 3.0.8 on 2021-04-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210414_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='media',
            field=models.FileField(blank=True, default='', upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
